# From python 3.7 docker images
FROM python:3.7-slim

# Application directory
WORKDIR /app

# Copy app fodler
COPY . /app

# intall dependencies
RUN apt-get update -y
RUN apt-get install 'ffmpeg' -y
RUN pip install -r requirements.txt

# Expose 8050 default port
EXPOSE 8050

# Run the application
ENTRYPOINT ["python"]
CMD ["app.py"]
